CREATE SCHEMA `epaybill` ;

'pay_ccb table'
CREATE TABLE `epaybill`.`pay_ccb` (
  `id` INT NOT NULL,
  `cc_number` VARCHAR(16) NOT NULL,
  `email_address` VARCHAR(50) NULL,
  `schedued_amount_pay` DOUBLE NOT NULL,
  `cc_typle` VARCHAR(10) NOT NULL,
  `contact_number` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));
  
  
  SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `epaybill`.`invocies` (
  `id` INT(11) NOT NULL,
  `external_aknowledgement` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `pay_referance_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invocies_pay_ccb_idx` (`pay_referance_id` ASC),
  CONSTRAINT `fk_invocies_pay_ccb`
    FOREIGN KEY (`pay_referance_id`)
    REFERENCES `epaybill`.`pay_ccb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `epaybill`.`pay_ccb` 
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;